WITH CON AS 
(
SELECT

L.SOURCE,
L.BUSINESS_PARTNER_ID SUPPLIER_ID,
CASE
    WHEN L.BUSINESS_PARTNER_ID = 510668 THEN 510650
     WHEN L.BUSINESS_PARTNER_ID = 10007163 THEN 510341
      ELSE L.BUSINESS_PARTNER_ID END SUPPLIER,
'ASN' || '' || L.TC_PURCHASE_ORDERS_ID RCVD_PO,
Q.ANS_TEXT DELIVERY_NBR, --McCains only
CAST(L.RCVD_DTTM AS DATE) RCVD_DATE,
CAST(L.EXPIRATION_DATE AS DATE) EXPIRATION_DATE,
CASE WHEN L.ITEM_NAME LIKE '%4615%' THEN '82130' WHEN L.ITEM_NAME LIKE  '%70177%' THEN '202550' END PRODUCT, --McCains only
L.ITEM_NAME,
C.DESCRIPTION,
L.TC_LPN_ID,
F.DESCRIPTION LPN_STATUS,
CASE WHEN CASE WHEN W.ON_HAND_QTY IS NULL THEN 0 ELSE W.ON_HAND_QTY END = 0 THEN 'CONSUMED' ELSE 'AVAILABLE' END PRD_STATUS,
CASE WHEN K.IS_LOCKED IS NULL THEN '-' ELSE K.IS_LOCKED END IS_LOCKED,
CASE WHEN K.INVENTORY_LOCK_CODE IS NULL THEN '-' ELSE K.INVENTORY_LOCK_CODE END INVENTORY_LOCK_CODE,
CASE WHEN L.TRACKING_NBR IS NULL THEN '-' ELSE L.TRACKING_NBR END SSCC,
D.BATCH_NBR,
D.RECEIVED_QTY,
CASE WHEN W.ON_HAND_QTY IS NULL THEN 0 ELSE W.ON_HAND_QTY END ON_HAND_QTY,
CAST(I.LAST_ADJ_DATE AS DATE) LAST_ADJ_DATE,
I.ADJUSTMENT,
'CTN' IP_UOM, --McCains only
1 PLT_SPACES, --McCains only
CASE WHEN T.PICKED IS NULL THEN 0 ELSE T.PICKED END PICKED,
Z.TRNSFR_DATE,
Z.TC_ORDER_ID TRNSFR_SALES_ORDER,
 CASE WHEN Z.O_FACILITY_ALIAS_ID  IN ('484','478') THEN  Z.D_FACILITY_ALIAS_ID 
    ELSE  UPPER(REPLACE(Z.D_FACILITY_NAME,'Martin Brower',''))  END TRNSFR_LOCATION,
CASE WHEN Z.TRANSFERRED IS NULL THEN 0 ELSE Z.TRANSFERRED END TRNSFR_QTY,
CASE 
     WHEN W.ON_HAND_QTY <=0  OR  W.ON_HAND_QTY IS NULL AND DATEDIFF(DAY,L.RCVD_DTTM, CAST(CONVERT_TIMEZONE('Australia/Sydney', CURRENT_TIMESTAMP()) AS DATE)) > 182 THEN 'NO'
     WHEN W.ON_HAND_QTY <=0  OR  W.ON_HAND_QTY IS NULL AND DATEDIFF(DAY,I.LAST_ADJ_DATE, CAST(CONVERT_TIMEZONE('Australia/Sydney', CURRENT_TIMESTAMP()) AS DATE)) > 182 THEN 'NO'
     ELSE 'YES'
     END AS ROW_RANGE



FROM "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."LPN" L

LEFT JOIN "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."INVENTORY" W ON W.TC_LPN_ID = L.TC_LPN_ID AND W.SOURCE = L.SOURCE
LEFT JOIN "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."ITEM_CBO" C ON C.ITEM_ID = L.ITEM_ID AND C.SOURCE = L.SOURCE

LEFT JOIN

(SELECT

D.SOURCE,
D.LPN_ID,
REPLACE(REPLACE(D.ITEM_NAME,'QR',''),'CON','') ITEM_NAME,
B.BATCH_NBR,
SUM(D.RECEIVED_QTY) RECEIVED_QTY,
S.SHIPPED_QTY

FROM "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."LPN_DETAIL" D

LEFT JOIN "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."LPN" L ON L.LPN_ID = D.LPN_ID AND L.SOURCE = D.SOURCE

--BATCH_NBR
LEFT JOIN

(SELECT

DISTINCT

D.SOURCE,
D.LPN_ID,
D.BATCH_NBR

FROM "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."LPN_DETAIL" D

WHERE D.BATCH_NBR IS NOT NULL) B ON B.LPN_ID = D.LPN_ID AND B.SOURCE = D.SOURCE

--SHIP_QTY
LEFT JOIN

(SELECT

DISTINCT

D.SOURCE,
D.LPN_ID,
D.SHIPPED_QTY

FROM "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."LPN_DETAIL" D

QUALIFY ROW_NUMBER() OVER (PARTITION BY D.LPN_ID ORDER BY D.PKEY_LPN_ID DESC) = 1) S ON S.LPN_ID = D.LPN_ID AND S.SOURCE = D.SOURCE

GROUP BY

D.SOURCE,
D.LPN_ID,
REPLACE(REPLACE(D.ITEM_NAME,'QR',''),'CON',''),
B.BATCH_NBR,
S.SHIPPED_QTY)


 D ON D.LPN_ID = L.LPN_ID AND D.SOURCE = L.SOURCE



LEFT JOIN "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."LPN_FACILITY_STATUS" F ON F.LPN_FACILITY_STATUS = L.LPN_FACILITY_STATUS AND F.SOURCE = L.SOURCE AND F.INBOUND_OUTBOUND_INDICATOR = 'I'
LEFT JOIN (SELECT K.SOURCE, K.INVENTORY_LOCK_CODE, K.TC_LPN_ID, 'Y' IS_LOCKED FROM "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."LPN_LOCK" K GROUP BY K.SOURCE, K.INVENTORY_LOCK_CODE, K.TC_LPN_ID) K ON K.TC_LPN_ID = L.TC_LPN_ID AND K.SOURCE = L.SOURCE
LEFT JOIN (SELECT Q.SOURCE, Q.QUES_MASTER_ID, Q.ANS_TEXT, Q.REF_VALUE FROM "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."QUESTION_ANS" Q WHERE Q.QUES_MASTER_ID IN ('1419')) Q ON Q.SOURCE = L.SOURCE AND Q.REF_VALUE = 'ASN' || '' || L.TC_PURCHASE_ORDERS_ID --McCains only

--ADJUSTMENTS
LEFT JOIN

(SELECT

T.SOURCE,
--T.TRAN_TYPE,
--T.TRAN_CODE,
T.CNTR_NBR,
MAX(T.CREATE_DATE_TIME) LAST_ADJ_DATE,
--T.NBR_UNITS,
SUM(T.REF_FIELD_2) ADJUSTMENT

FROM "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."PROD_TRKG_TRAN" T WHERE T.TRAN_TYPE = '600' AND T.TRAN_CODE NOT IN ('008')

GROUP BY

T.SOURCE,
T.CNTR_NBR) I ON I.CNTR_NBR = L.TC_LPN_ID AND I.SOURCE = L.SOURCE

--PICKED
LEFT JOIN

(SELECT

T.SOURCE,
T.CNTR_NBR TC_LPN_ID,
S.LPN_FACILITY_STATUS STAT_CODE,
Z.DESCRIPTION LPN_STATUS,

SUM(T.QTY_PULLD) PICKED

FROM "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."TASK_DTL" T

LEFT JOIN "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."ORDERS" O ON O.TC_ORDER_ID = T.TC_ORDER_ID AND O.SOURCE = T.SOURCE
LEFT JOIN "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."LPN" L ON L.TC_LPN_ID = T.CNTR_NBR AND L.SOURCE = T.SOURCE
LEFT JOIN (SELECT L.SOURCE, L.TC_LPN_ID, L.LPN_FACILITY_STATUS FROM "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."LPN" L) S ON S.TC_LPN_ID = T.TASK_CMPL_REF_NBR AND S.SOURCE = L.SOURCE
LEFT JOIN "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."LPN_FACILITY_STATUS" Z ON Z.LPN_FACILITY_STATUS = S.LPN_FACILITY_STATUS AND Z.SOURCE = S.SOURCE AND Z.INBOUND_OUTBOUND_INDICATOR = 'O'

WHERE T.INVN_NEED_TYPE = '50' AND S.LPN_FACILITY_STATUS < 99

GROUP BY

T.SOURCE,
T.CNTR_NBR,
S.LPN_FACILITY_STATUS,
Z.DESCRIPTION) T ON T.TC_LPN_ID = L.TC_LPN_ID

--TRANSFERRED
LEFT JOIN

 

(SELECT

A.SOURCE,
A.TC_ORDER_ID,
A.CNTR_NBR,
--H.DSP_LOCN,
O.D_FACILITY_ALIAS_ID,
REPLACE(O.D_FACILITY_NAME,'DC','') D_FACILITY_NAME,
O.O_FACILITY_ALIAS_ID,
O.TRANSFER_DATE TRNSFR_DATE,
A.LOADDATE,
D.QTY_PULLD TRANSFERRED

FROM

(SELECT

A.SOURCE,
A.TC_ORDER_ID,
A.CNTR_NBR,
MAX(A.LOADDATE) LOADDATE

FROM "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."ALLOC_INVN_DTL" A

--LEFT JOIN "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."LOCN_HDR" H ON H.LOCN_ID = A.PULL_LOCN_ID AND H.SOURCE = A.SOURCE

WHERE A.INVN_NEED_TYPE = 2 AND A.STAT_CODE < 99

GROUP BY

A.SOURCE,
A.TC_ORDER_ID,
A.CNTR_NBR) A

--TRANSFER DATE
LEFT JOIN (SELECT O.SOURCE, O.TC_ORDER_ID, CAST(O.PICKUP_START_DTTM AS DATE) TRANSFER_DATE, O.D_FACILITY_ALIAS_ID,O.D_FACILITY_NAME,O.O_FACILITY_ALIAS_ID FROM "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."ORDERS" O) O ON O.TC_ORDER_ID = A.TC_ORDER_ID AND O.SOURCE = A.SOURCE

LEFT JOIN "MB_ANZ_DW_PRD"."DM_RAW_WMS_ANZ"."ALLOC_INVN_DTL" D ON D.CNTR_NBR = A.CNTR_NBR AND D.TC_ORDER_ID = A.TC_ORDER_ID AND D.SOURCE = A.SOURCE AND D.LOADDATE = A.LOADDATE
) Z ON Z.CNTR_NBR = L.TC_LPN_ID AND Z.SOURCE = L.SOURCE

WHERE L.LPN_FACILITY_STATUS < 99 AND SUBSTRING(L.ITEM_NAME,1,1) IN ('C','V','Q') OR SUPPLIER IN ('300926','300927','510341','10010683')

ORDER BY

--Z.TRNSFR_DATE,
--Z.TC_ORDER_ID,
F.DESCRIPTION,
L.ITEM_NAME,
L.TC_LPN_ID

 )
SELECT 
  CON.*
 ,CAST(SOURCE || SUPPLIER AS INT) AS SUPPLIER_DC_ID
 ,CASE WHEN ITEM_NAME LIKE '%CON5358039%' AND SUPPLIER = 510341 THEN 'L7197NZ'
       WHEN ITEM_NAME LIKE '%NS9700812%' AND SUPPLIER = 510341 THEN 'L20008NZ'
       WHEN ITEM_NAME LIKE '%NS9700813%' AND SUPPLIER = 510341 THEN 'L25001NZ'
       ELSE NULL 

       END AS PRODUCT_CODE
 
FROM 

CON

LEFT JOIN MB_ANZ_DW_PRD.CERTIFIED_ANZ.DIMTIME TIME 
  ON TIME.GREGORIAN = RCVD_DATE



WHERE 

  -- TIME.WEEKENDING 
    --  BETWEEN  DATEADD(WEEK,-52,GETDATE()) and (SELECT dateadd(day,+8, getdate()))
     ROW_RANGE = 'YES'
  --  AND SUPPLIER = '510341'
   

ORDER BY 
  RCVD_DATE DESC